package io.github.bagu.simplelogger;

/**
 * Represents a destination for log events.
 * <p>
 * Implementations of this interface act as the endpoint for log messages generated by
 * {@link Logger}s. Log sinks can write events to files, consoles, networks, or any custom endpoints.
 * <p>
 * Thread safety: All methods must be safe to call concurrently from multiple threads.
 * <p>
 * Exception handling: Implementations must not throw exceptions. If an error occurs,
 * it should be handled internally or via a {@link ExceptionHandler}.
 *
 * @see Logger
 * @see LogEvent
 */
public interface LogSink extends AutoCloseable {
    /**
     * Accepts a log event and writes it to this sink.
     *
     * @param event the event to write
     */
    void accept(LogEvent event);

    /**
     * Closes the sink and releases any associated resources.
     * <p>
     * Implementations must be idempotent.
     */
    @Override void close();

    /**
     * Checks whether the sink has been closed.
     *
     * @return {@code true} if the sink is closed, otherwise {@code false}
     */
    boolean isClosed();
}
